name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))
name=str(input("Enter name : "))

names = ["Joe","Sally","Jim","June","Betty","Bill","Sara","Zak","Anne","Kate"]
print(names, sep = ", ")

names.append('Joe')
names.append('Sally')
names.append('Jim')
names.append('June')
names.append('Betty')
names.append('Bill')
names.append('Sara')
names.append('Zak')
names.append('Anne')
names.append('Kate')

len(names)
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
print(names.pop(0))
